In [1]:
import warnings
warnings.filterwarnings("ignore")

# 10.Introduction to Artificial Neural Networks

#### 感知器（Perceptron）
<img src="./pic/Linear-threshold-unit.png"  height="400" width="600" align="left"/>

###### 感知器的每一个neuron都是线性的，无法应对复杂情况

In [2]:
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

In [5]:
# sklearn的Perceptron使用的就是SGDClassifier使用loss="perceptron",learning_rate="constant",eta0=1,penalty=None
# 它无概率展示，只会根据一个threshold预测，因此逻辑回归优于它
iris = load_iris()
X = iris.data[:,(2,3)]
y = (iris.target == 0).astype(np.int)
per_clf = Perceptron(random_state=42)
per_clf.fit(X,y)

y_pred = per_clf.predict([[2,0.5]])

In [6]:
y_pred

array([1])

### MLP和反向传播
perceptron存在无法解决异或的问题，但是发现可以通过迭加多层感知机解决，也就是MLP。
MLP由一个输入层+多个隐藏层+一个输出层构成
<img src="./pic/MLP.png"  height="400" width="600" align="left"/>

In [7]:
import tensorflow as tf 

In [10]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

In [14]:
X_train = X_train.astype(np.float32).reshape(-1, 28*28) / 255.0
X_test = X_test.astype(np.float32).reshape(-1, 28*28) / 255.0
y_train = y_train.astype(np.int32)
y_test = y_test.astype(np.int32)
X_valid, X_train = X_train[:5000], X_train[5000:]
y_valid, y_train = y_train[:5000], y_train[5000:]

In [18]:
# 高阶API
feature_columns = [tf.feature_column.numeric_column("X", shape=[28 * 28])]
dnn_clf = tf.estimator.DNNClassifier(hidden_units=[300,100],n_classes=10,feature_columns=feature_columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/3s/74j36f697v54z25bvz3gwhd00000gn/T/tmpcot_ncd8', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1a30efa898>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [19]:
input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"X": X_train}, y=y_train, num_epochs=40, batch_size=50, shuffle=True)
dnn_clf.train(input_fn=input_fn)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/3s/74j36f697v54z25bvz3gwhd00000gn/T/tmpcot_ncd8/model.ckpt.
INFO:tensorflow:loss = 116.691, step = 1
INFO:tensorflow:global_step/sec: 46.4208
INFO:tensorflow:loss = 15.6692, step = 101 (2.156 sec)
INFO:tensorflow:global_step/sec: 50.4843
INFO:tensorflow:loss = 10.3279, step = 201 (1.981 sec)
INFO:tensorflow:global_step/sec: 50.6361
INFO:tensorflow:loss = 12.4677, step = 301 (1.975 sec)
INFO:tensorflow:global_step/sec: 50.8517
INFO:tensorflow:loss = 21

INFO:tensorflow:loss = 0.709555, step = 7001 (2.024 sec)
INFO:tensorflow:global_step/sec: 50.8028
INFO:tensorflow:loss = 0.185247, step = 7101 (1.968 sec)
INFO:tensorflow:global_step/sec: 51.8364
INFO:tensorflow:loss = 2.81146, step = 7201 (1.929 sec)
INFO:tensorflow:global_step/sec: 50.4277
INFO:tensorflow:loss = 0.240466, step = 7301 (1.983 sec)
INFO:tensorflow:global_step/sec: 51.1646
INFO:tensorflow:loss = 0.155802, step = 7401 (1.955 sec)
INFO:tensorflow:global_step/sec: 50.4612
INFO:tensorflow:loss = 0.244573, step = 7501 (1.981 sec)
INFO:tensorflow:global_step/sec: 47.8352
INFO:tensorflow:loss = 4.06218, step = 7601 (2.091 sec)
INFO:tensorflow:global_step/sec: 44.8137
INFO:tensorflow:loss = 0.637534, step = 7701 (2.231 sec)
INFO:tensorflow:global_step/sec: 46.7511
INFO:tensorflow:loss = 0.457968, step = 7801 (2.140 sec)
INFO:tensorflow:global_step/sec: 48.4669
INFO:tensorflow:loss = 0.480054, step = 7901 (2.063 sec)
INFO:tensorflow:global_step/sec: 50.2353
INFO:tensorflow:loss =

INFO:tensorflow:loss = 0.113857, step = 15301 (2.014 sec)
INFO:tensorflow:global_step/sec: 49.5257
INFO:tensorflow:loss = 0.036834, step = 15401 (2.019 sec)
INFO:tensorflow:global_step/sec: 51.6138
INFO:tensorflow:loss = 0.0201744, step = 15501 (1.937 sec)
INFO:tensorflow:global_step/sec: 51.0481
INFO:tensorflow:loss = 0.0829988, step = 15601 (1.959 sec)
INFO:tensorflow:global_step/sec: 52.122
INFO:tensorflow:loss = 0.0470227, step = 15701 (1.918 sec)
INFO:tensorflow:global_step/sec: 52.217
INFO:tensorflow:loss = 0.0774356, step = 15801 (1.915 sec)
INFO:tensorflow:global_step/sec: 50.9356
INFO:tensorflow:loss = 0.151203, step = 15901 (1.964 sec)
INFO:tensorflow:global_step/sec: 51.8167
INFO:tensorflow:loss = 0.0211514, step = 16001 (1.930 sec)
INFO:tensorflow:global_step/sec: 50.9459
INFO:tensorflow:loss = 0.127644, step = 16101 (1.963 sec)
INFO:tensorflow:global_step/sec: 51.4758
INFO:tensorflow:loss = 0.0268463, step = 16201 (1.942 sec)
INFO:tensorflow:global_step/sec: 52.1801
INFO:t

INFO:tensorflow:global_step/sec: 47.2369
INFO:tensorflow:loss = 0.0610985, step = 23601 (2.117 sec)
INFO:tensorflow:global_step/sec: 51.2797
INFO:tensorflow:loss = 0.0207088, step = 23701 (1.950 sec)
INFO:tensorflow:global_step/sec: 46.7836
INFO:tensorflow:loss = 0.0212648, step = 23801 (2.138 sec)
INFO:tensorflow:global_step/sec: 45.0556
INFO:tensorflow:loss = 0.00191904, step = 23901 (2.221 sec)
INFO:tensorflow:global_step/sec: 47.6461
INFO:tensorflow:loss = 0.0385164, step = 24001 (2.098 sec)
INFO:tensorflow:global_step/sec: 49.431
INFO:tensorflow:loss = 0.0911573, step = 24101 (2.023 sec)
INFO:tensorflow:global_step/sec: 50.7927
INFO:tensorflow:loss = 0.070143, step = 24201 (1.968 sec)
INFO:tensorflow:global_step/sec: 48.653
INFO:tensorflow:loss = 0.0419204, step = 24301 (2.055 sec)
INFO:tensorflow:global_step/sec: 50.5902
INFO:tensorflow:loss = 0.021448, step = 24401 (1.977 sec)
INFO:tensorflow:global_step/sec: 48.4848
INFO:tensorflow:loss = 0.0554336, step = 24501 (2.062 sec)
INF

INFO:tensorflow:global_step/sec: 47.3659
INFO:tensorflow:loss = 0.0108941, step = 31701 (2.111 sec)
INFO:tensorflow:global_step/sec: 46.5132
INFO:tensorflow:loss = 0.0114832, step = 31801 (2.150 sec)
INFO:tensorflow:global_step/sec: 45.8527
INFO:tensorflow:loss = 0.00359209, step = 31901 (2.181 sec)
INFO:tensorflow:global_step/sec: 46.7895
INFO:tensorflow:loss = 0.0210676, step = 32001 (2.137 sec)
INFO:tensorflow:global_step/sec: 48.0658
INFO:tensorflow:loss = 0.00775694, step = 32101 (2.081 sec)
INFO:tensorflow:global_step/sec: 47.5076
INFO:tensorflow:loss = 0.0143723, step = 32201 (2.105 sec)
INFO:tensorflow:global_step/sec: 46.105
INFO:tensorflow:loss = 0.0267598, step = 32301 (2.169 sec)
INFO:tensorflow:global_step/sec: 50.2699
INFO:tensorflow:loss = 0.00982285, step = 32401 (1.989 sec)
INFO:tensorflow:global_step/sec: 50.2507
INFO:tensorflow:loss = 0.00845598, step = 32501 (1.990 sec)
INFO:tensorflow:global_step/sec: 49.3616
INFO:tensorflow:loss = 0.015888, step = 32601 (2.026 sec

INFO:tensorflow:global_step/sec: 45.7994
INFO:tensorflow:loss = 0.019098, step = 39901 (2.183 sec)
INFO:tensorflow:global_step/sec: 46.6203
INFO:tensorflow:loss = 0.0195164, step = 40001 (2.145 sec)
INFO:tensorflow:global_step/sec: 49.7288
INFO:tensorflow:loss = 0.0473042, step = 40101 (2.011 sec)
INFO:tensorflow:global_step/sec: 50.5565
INFO:tensorflow:loss = 0.00816624, step = 40201 (1.977 sec)
INFO:tensorflow:global_step/sec: 48.4424
INFO:tensorflow:loss = 0.01775, step = 40301 (2.064 sec)
INFO:tensorflow:global_step/sec: 48.0772
INFO:tensorflow:loss = 0.00796074, step = 40401 (2.080 sec)
INFO:tensorflow:global_step/sec: 48.1284
INFO:tensorflow:loss = 0.0122701, step = 40501 (2.078 sec)
INFO:tensorflow:global_step/sec: 47.6832
INFO:tensorflow:loss = 0.0131698, step = 40601 (2.097 sec)
INFO:tensorflow:global_step/sec: 50.2343
INFO:tensorflow:loss = 0.00340529, step = 40701 (1.991 sec)
INFO:tensorflow:global_step/sec: 50.1375
INFO:tensorflow:loss = 0.0134514, step = 40801 (1.995 sec)


In [20]:
test_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"X": X_test}, y=y_test, shuffle=False)
eval_results = dnn_clf.evaluate(input_fn=test_input_fn)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-03-26-15:38:57
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/3s/74j36f697v54z25bvz3gwhd00000gn/T/tmpcot_ncd8/model.ckpt-44000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2019-03-26-15:38:59
INFO:tensorflow:Saving dict for global step 44000: accuracy = 0.9816, average_loss = 0.0960944, global_step = 44000, loss = 12.1638
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 44000: /var/folders/3s/74j36f697v54z25bvz3gwhd00000gn/T/tmpcot_ncd8/model.ckpt-44000


In [21]:
eval_results

{'accuracy': 0.98159999,
 'average_loss': 0.096094392,
 'loss': 12.163847,
 'global_step': 44000}

In [22]:
y_pred_iter = dnn_clf.predict(input_fn=test_input_fn)
y_pred = list(y_pred_iter)
y_pred[0]

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/3s/74j36f697v54z25bvz3gwhd00000gn/T/tmpcot_ncd8/model.ckpt-44000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


{'logits': array([ -4.74234152,   0.90434092,   5.8279891 ,   5.07642984,
         -5.37222815,  -6.42676258, -12.17822933,  27.4439373 ,
          0.54517782,   2.32133746], dtype=float32),
 'probabilities': array([  1.05117856e-14,   2.97851414e-12,   4.09555889e-10,
          1.93158906e-10,   5.59912580e-15,   1.95048013e-15,
          6.19886380e-18,   1.00000000e+00,   2.07977819e-12,
          1.22855103e-11], dtype=float32),
 'class_ids': array([7]),
 'classes': array([b'7'], dtype=object)}

In [25]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=int32)

In [49]:
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

In [80]:
reset_graph()

In [81]:
X = tf.placeholder(tf.float32, shape=(None,n_inputs), name="X")
y = tf.placeholder(tf.int32, shape=(None,10), name="y")

In [82]:
# 低阶API
n_inputs = 28*28
n_hidden1 = 300
n_hidden2 = 100
n_outputs = 10


In [83]:
#定义全连接层
def neuron_layer(X, n_neurons, name, activation=None):
    with tf.name_scope(name):
        n_inputs = int(X.get_shape()[1])
        stddev = 2 / np.sqrt(n_inputs)
        #tf.truncated_normal(shape, mean, stddev) :shape表示生成张量的维度，mean是均值，stddev是标准差。这个函数产生正太分布，均值和标准差自己设定。这是一个截断的产生正太分布的函数，就是说产生正太分布的值如果与均值的差值大于两倍的标准差，那就重新生成。和一般的正太分布的产生随机数据比起来，这个函数产生的随机数与均值的差距不会超过两倍的标准差，但是一般的别的函数是可能的。
        init = tf.truncated_normal((n_inputs, n_neurons), stddev=stddev)
        W = tf.Variable(init, name="weights")
        b = tf.Variable(tf.zeros([n_neurons]), name="biases")
        z = tf.matmul(X,W) + b
        if activation =="relu":
            return tf.nn.relu(z)
        else:
            return z

In [84]:
with tf.name_scope("dnn"):
    hidden1 = neuron_layer(X,n_hidden1,"hidden1",activation="relu")
    hidden2 = neuron_layer(hidden1,n_hidden2,"hidden2",activation="relu")
    logits = neuron_layer(hidden2,n_outputs,"outputs")
# tf.contrib.layers.fully_connected方法有同样作用，它默认是用"relu"激活函数，
# with tf.name_scope("dnn1"):
#     hidden1_1 = tf.contrib.layers.fully_connected(X,n_hidden1,scope="hidden1_1")
#     hidden2_1 = tf.contrib.layers.fully_connected(hidden1,n_hidden2,scope="hidden2_1")
#     logits_1 = tf.contrib.layers.fully_connected(hidden2,n_outputs,scope="outputs_1",activation_fn=None)

In [86]:
#定义损失
with tf.name_scope("loss"):
    #这是一个TensorFlow中经常需要用到的函数。官方文档里面有对它详细的说明，
    #传入的logits为神经网络输出层的输出，shape为[batch_size，num_classes]，
    #传入的label为一个一维的vector，长度等于batch_size，每一个值的取值区间必须是[0，num_classes)，
    #其实每一个值就是代表了batch中对应样本的类别。
    #作用:计算softmax激活函数并计算交叉熵
    #和tf.nn.sparse_softmax_cross_entropy_with_logits区别:logits和labels的shape都是[batch_size, num_classes] 
    #效果:对于稀疏向量效率更高
    #xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y,logits=logits)
    xentropy = tf.nn.softmax_cross_entropy_with_logits_v2(labels=y,logits=logits)
    loss = tf.reduce_mean(xentropy,name="loss")

In [87]:
#定义训练过程
learning_rate = 0.01

with tf.name_scope("train"):
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
    train_op = optimizer.minimize(loss)

In [91]:
# 评估模型,这里只使用准确性评估
with tf.name_scope("eval"):
    #表示每个样本的预测结果的前K个最大的数里面是否含有target中的值
#     correct = tf.nn.in_top_k(logits,y,1)
    correct_prediction = tf.equal(tf.argmax(logits,1), tf.argmax(y,1))

    accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))

In [92]:
init = tf.global_variables_initializer()
saver = tf.train.Saver()

In [93]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/Users/zhen.huaz/work/github/ml-demo/demo_data/MNIST_data/", one_hot=True)

Extracting /Users/zhen.huaz/work/github/ml-demo/demo_data/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/zhen.huaz/work/github/ml-demo/demo_data/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/zhen.huaz/work/github/ml-demo/demo_data/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zhen.huaz/work/github/ml-demo/demo_data/MNIST_data/t10k-labels-idx1-ubyte.gz


In [94]:
#执行过程
n_epochs = 400
batch_size = 50

with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for iteration in range(mnist.train.num_examples // batch_size):
            X_batch, y_batch = mnist.train.next_batch(batch_size)
            sess.run(train_op,feed_dict={X:X_batch,y:y_batch})
        acc_train = accuracy.eval(feed_dict={X:X_batch,y:y_batch})
        acc_test = accuracy.eval(feed_dict={X:mnist.test.images,y:mnist.test.labels})
        
        print(epoch,"Train accuracy:",acc_train,"Test accuracy:",acc_test)
    save_path = saver.save(sess,"/tmp/my_model_final.ckpt")

0 Train accuracy: 0.9 Test accuracy: 0.9128
1 Train accuracy: 0.94 Test accuracy: 0.9291
2 Train accuracy: 0.92 Test accuracy: 0.9398
3 Train accuracy: 0.96 Test accuracy: 0.945
4 Train accuracy: 0.92 Test accuracy: 0.9511
5 Train accuracy: 0.94 Test accuracy: 0.9543
6 Train accuracy: 0.98 Test accuracy: 0.9556
7 Train accuracy: 0.96 Test accuracy: 0.9594
8 Train accuracy: 0.92 Test accuracy: 0.9625
9 Train accuracy: 0.96 Test accuracy: 0.9643
10 Train accuracy: 0.98 Test accuracy: 0.965
11 Train accuracy: 0.94 Test accuracy: 0.9669
12 Train accuracy: 1.0 Test accuracy: 0.9691
13 Train accuracy: 0.94 Test accuracy: 0.9683
14 Train accuracy: 1.0 Test accuracy: 0.9694
15 Train accuracy: 1.0 Test accuracy: 0.9713
16 Train accuracy: 1.0 Test accuracy: 0.9712
17 Train accuracy: 0.98 Test accuracy: 0.9712
18 Train accuracy: 1.0 Test accuracy: 0.9725
19 Train accuracy: 1.0 Test accuracy: 0.973
20 Train accuracy: 0.98 Test accuracy: 0.9735
21 Train accuracy: 1.0 Test accuracy: 0.9737
22 Train 

181 Train accuracy: 1.0 Test accuracy: 0.9814
182 Train accuracy: 1.0 Test accuracy: 0.9813
183 Train accuracy: 1.0 Test accuracy: 0.9814
184 Train accuracy: 1.0 Test accuracy: 0.9815
185 Train accuracy: 1.0 Test accuracy: 0.9813
186 Train accuracy: 1.0 Test accuracy: 0.9814
187 Train accuracy: 1.0 Test accuracy: 0.9816
188 Train accuracy: 1.0 Test accuracy: 0.9815
189 Train accuracy: 1.0 Test accuracy: 0.9813
190 Train accuracy: 1.0 Test accuracy: 0.9815
191 Train accuracy: 1.0 Test accuracy: 0.9816
192 Train accuracy: 1.0 Test accuracy: 0.9817
193 Train accuracy: 1.0 Test accuracy: 0.9813
194 Train accuracy: 1.0 Test accuracy: 0.9808
195 Train accuracy: 1.0 Test accuracy: 0.9815
196 Train accuracy: 1.0 Test accuracy: 0.9815
197 Train accuracy: 1.0 Test accuracy: 0.9812
198 Train accuracy: 1.0 Test accuracy: 0.9815
199 Train accuracy: 1.0 Test accuracy: 0.9815
200 Train accuracy: 1.0 Test accuracy: 0.9813
201 Train accuracy: 1.0 Test accuracy: 0.9814
202 Train accuracy: 1.0 Test accur

360 Train accuracy: 1.0 Test accuracy: 0.9815
361 Train accuracy: 1.0 Test accuracy: 0.9816
362 Train accuracy: 1.0 Test accuracy: 0.9815
363 Train accuracy: 1.0 Test accuracy: 0.9815
364 Train accuracy: 1.0 Test accuracy: 0.9814
365 Train accuracy: 1.0 Test accuracy: 0.9814
366 Train accuracy: 1.0 Test accuracy: 0.9815
367 Train accuracy: 1.0 Test accuracy: 0.9814
368 Train accuracy: 1.0 Test accuracy: 0.9814
369 Train accuracy: 1.0 Test accuracy: 0.9814
370 Train accuracy: 1.0 Test accuracy: 0.9815
371 Train accuracy: 1.0 Test accuracy: 0.9814
372 Train accuracy: 1.0 Test accuracy: 0.9815
373 Train accuracy: 1.0 Test accuracy: 0.9817
374 Train accuracy: 1.0 Test accuracy: 0.9813
375 Train accuracy: 1.0 Test accuracy: 0.9815
376 Train accuracy: 1.0 Test accuracy: 0.9812
377 Train accuracy: 1.0 Test accuracy: 0.9814
378 Train accuracy: 1.0 Test accuracy: 0.9814
379 Train accuracy: 1.0 Test accuracy: 0.9813
380 Train accuracy: 1.0 Test accuracy: 0.9814
381 Train accuracy: 1.0 Test accur

In [1]:
with tf.Session() as sess:
    saver.restore(sess,"/tmp/my_model_final.ckpt")
    X_new_scaled = X_test
    Z = logits.eval(feed_dict={X:X_new_scaled})
    y_pred = np.argmax(Z, axis=1)

NameError: name 'tf' is not defined

In [97]:
y_pred

array([7, 2, 1, ..., 4, 5, 6])

In [98]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=int32)

### Fine-Tuning Network Hyperparameters
1.网络拓扑
2.深度----（简单一般优先尝试一到2层隐藏层，对于复杂任务再往上提升抽象）
3.每层neurons数----（增加层数一般优于增加单层的neurons数）
4.每层的激活函数----（一般使用relu优于其他激活函数，因为它不会饱和，sigmoid的双曲线都会在1的时候饱和；对于输出层，分类一般使用softmax，回归不设置）
5.初始化的权重
...

一般使用randomized search在第二张提过，或是Oscar工具可以用来调参